---
- name: "delete"
  package:
    name: "{{ packages_del }}"
    state: absent
    purge: yes
  when: packages_del is defined
  tags:
    - packages
    - del

- name: "command-not-found"
  package:
    name: command-not-found
  notify: update command-not-found
  tags:
    - packages
    - command-not-found
...
